package org.example.ComponentsPack;

public enum TileType {
    CABINS,
    ALIENCABINS,
    CARGOHOLDS,
    SPECIALCARGOHOLDS,
    BATTERYCOMPONENTS,
    LIFESUPPORTSISTEM,
    SHIELDGENERATOR,
    STRUCTURALNODES,
    CENTRALCABIN,
    ENGINE,
    DOUBLEENGINE,
    CANNON,
    DOUBLECANNON;
}
